sudo: required
language: cpp
compiler:
    - gcc
env:
    matrix:
        - FIREFOXVERSION="stable"
        - FIREFOXVERSION="ESR"
notifications:
    email: false
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - test/install-firefox.sh
script:
    - test/runtests.sh